console.log('Hello world !!!')
console.log('Curso de JavaScript ...')
console.log('Eu estou programando em js !!!')
console.log('O professor é o Luiz Otávio Miranda.')
console.log('Eu estou lendo de mais os e-mails.')
console.log('Estou adorando o novo curso.')
console.log('Mais um dia de estudo.')
console.log('Mais um avanço.')
console.log('Mais um aprendizado.')
console.log('')