console.log('Hi, my name is Andreson')
console.log(typeof 'Hi, my name is Andreson')
console.log('I wanted to buy a car')
console.log(typeof 'I wanted to buy a car')
console.log(`Test`)
console.log(typeof `Test`)
console.log(`How are you ???`)
console.log(typeof `How are you ???`)
console.log('Infinity')
console.log(typeof 'Infinity')
console.log(Infinity)
console.log(typeof Infinity)
